### ISSUE TITLE
Add login for app

### ISSUE THREAD

**Issue by sharonkass** [RoboTigers/FRCScout2020#7]
**Data Requirements**

- Username (e.g., Ryan)
- Role (Admin or Scout)
- Password

**Functional Requirements**

- Ability to know Username and Role from various components (e.g., MatchReportList should only allow admins to edit matches)

Regarding implementation there are no requirements; anything quick and easy for now. We can enhance in future years.

**Comment by MGerrior** [comment]
#35 has most of the instructions, but with regards to knowing the username/role from various components, I think you can also use the `AuthConsumer` within your JSX if desired, something like:

```jsx
<AuthConsumer>
  {({ user }) => (
    <div>Current user is: {user.name} and role is {user.role}
  )}
</AuthConsumer>
```

Something like that, may need to tweak it. I made the consumer but didn't actually use it anywhere, just the provider.
